### ISSUE TITLE
Remove suggested `rgdal` as soon as possible

### ISSUE THREAD

**Issue by rsbivand** [joeroe/rpaleoclim#18]
`raster` stopped using `rgdal` and `rgeos` in favour of `terra` in September 2022; `rgdal`, `rgeos` and `maptools` will be archived in October 2023 (see: https://r-spatial.org/r/2023/05/15/evolution4.html, https://r-spatial.github.io/evolution/). When `rgdal` is not on the library path, this is the CMD check log:
[00check.log](https://github.com/joeroe/rpaleoclim/files/11743252/00check.log) with test details: 
[testthat.Rout.zip](https://github.com/joeroe/rpaleoclim/files/11743259/testthat.Rout.zip)
Almost certainly, both the Suggests: listing and the test are left over from before https://github.com/joeroe/rpaleoclim/issues/10.

**Comment by rsbivand** [comment]
@joeroe Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by joeroe** [comment]
Thank you for the reminder @rsbivand. This will be on its way to CRAN as soon as they're accepting submissions again (#19).

**Comment by rsbivand** [comment]
Looks OK when checking without retiring packages on the library path: 
[00check.log](https://github.com/joeroe/rpaleoclim/files/12253726/00check.log)
