### ISSUE TITLE
Issues pulling specific paleoclim rasters

### ISSUE THREAD

**Issue by jhavill** [joeroe/rpaleoclim#2]
I'm having issues downloading specific raster sets (at any resolution). These include the LGM and MPWP right now, but may also include others that I haven't tested yet. Any ideas why this might be?

trying URL 'http://sdmtoolbox.org/paleoclim.org/data/chelsa_LGM/chelsa_LGM_v1_2B_r10m.zip'
Content type 'application/zip' length 17468981 bytes (16.7 MB)

downloaded 63 KB

Error in utils::download.file(url, tmpfile, "auto") : 
  download from 'http://sdmtoolbox.org/paleoclim.org/data/chelsa_LGM/chelsa_LGM_v1_2B_r10m.zip' failed
In addition: Warning messages:
1: In utils::download.file(url, tmpfile, "auto") :
  downloaded length 65380 != reported length 17468981
2: In utils::download.file(url, tmpfile, "auto") :
  URL 'http://sdmtoolbox.org/paleoclim.org/data/chelsa_LGM/chelsa_LGM_v1_2B_r10m.zip': Timeout of 60 seconds was reached

**Comment by joeroe** [comment]
Thanks for using the package! I can't reproduce this myself. It could be a temporary server problem with sdmtoolbox.org, or do you get this consistently?

**Comment by jhavill** [comment]
It appears to be intermittent issues, now other rasters are having issues downloading that I didn't have issues with previously.

**Comment by jhavill** [comment]
If a raster is unsuccessfully downloaded though, and I make an attempt to re-download it, I do receive this error though:

Error in x[[1]] : subscript out of bounds
In addition: Warning message:
In utils::unzip(file, exdir = tmpdir) : error 1 in extracting from zip file

**Comment by joeroe** [comment]
That is a bug. The function should clean up the partially downloaded file.

In the meantime, you should be able to work around it by setting `skip_cache = TRUE` when you redownload.

**Comment by jhavill** [comment]
Excellent, worked perfectly!  Thanks!
